In [2]:
import torch
import numpy as np

In [6]:
A = torch.tensor([[3, 4], [0, 0], [5, 12]], dtype=torch.float32)
torch.norm(A, p=2, dim=1)[:, None]

tensor([[ 5.],
        [ 0.],
        [13.]])

In [39]:
def pairwise_l2_sq(x, y):
    dot = torch.mm(x.double(), torch.t(y.double()))
    left_norms = torch.pow(torch.norm(x, p=2, dim=1), 2)[:, None]
    right_norms = torch.pow(torch.norm(y, p=2, dim=1), 2)[None, :]
    dist = left_norms - 2 * dot + right_norms
    dist = torch.clamp(dist, min=0)
    return dist.float()

A = torch.tensor([[i, i+1] for i in range(137564)], dtype=torch.float32)

mesh_x, mesh_y = torch.meshgrid(torch.arange(0, 3), torch.arange(7), indexing='ij')
mask = mesh_x == mesh_y

print(mesh_x)
print(mesh_y)

print(mask)

tensor([[0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2]])
tensor([[0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6]])
tensor([[ True, False, False, False, False, False, False],
        [False,  True, False, False, False, False, False],
        [False, False,  True, False, False, False, False]])
